"""Subalgebra-membership test for the cylindrical towers (the
decision-point computation for the cylindrical BCD dictionary
analysis).

Question: do the cylindrical charges admit representatives (mod total
derivatives) inside the subalgebra of the mixed invariant algebra
generated by finitely many low-spin singlet currents?

  - A<=2k = subalgebra generated by the X boson and all Y-singlets
    of spin <= 2k (equivalently by (11), (22), ..., (kk))

For each solution and charge I3 (weight 4), I5 (weight 6), I7
(weight 8; exact kernel representative at a curve point), we test
class membership in span(subalgebra weight-w elements) + Im d.
Non-membership at a curve point is generic by semicontinuity.

Certified conditions (all six asserted, fail-closed; audit round 2):
I3 not in A<=2, I3 in A<=4; I5 not in A<=4, I5 in A<=6; I7 not in
A<=6, I7 in A<=8 -- a FINITE-RANGE ladder through I7.  This excludes
the direct LV rank-2 W(2,4) subalgebra match (I5 already needs a
weight-6 singlet).  It does NOT exclude a finite W(2,4,6,8)-type
algebra containing all higher charges; all-spin structural claims
are outside this computation's reach.  Retained controls: a positive
product control, a d-exact control, and a d-exact-shift negative
control run before the main tests."""
import sys
from fractions import Fraction as F

import collapsed
import mixed_engine
mixed_engine.residue_mixed_mono = collapsed.residue_mixed_mono_smart
from invariant_engine import curve_point
from mixed_engine import (cyl_P4, d_mixed_mono, gen_mixed_basis,
                          residue_mixed_cur, spin_mixed)
from sparse_linalg import SparsePivots, _to_int_vec, genuine_kernel_sparse


def d_cur(cur):
    out = {}
    for m, c in cur.items():
        for m2, c2 in d_mixed_mono(m).items():
            out[m2] = out.get(m2, 0) + c * c2
    return {m: c for m, c in out.items() if c}


def mult(c1, c2):
    out = {}
    for m1, a in c1.items():
        for m2, b in c2.items():
            m = (tuple(sorted(m1[0] + m2[0])),
                 tuple(sorted(m1[1] + m2[1])))
            out[m] = out.get(m, 0) + a * b
    return out


def blocks(pair, wmax):
    """(current, weight) for d^c of the singlet `pair` up to wmax."""
    base = {((), (pair,)): F(1)}
    w0 = sum(pair)
    out = []
    cur = base
    w = w0
    while w <= wmax:
        out.append((cur, w))
        cur = d_cur(cur)
        w += 1
    return out


def x_monos(u):
    """X-monomials of weight u with an even number of letters."""
    res = []

    def rec(rem, minpart, acc):
        if rem == 0:
            if len(acc) % 2 == 0:
                res.append(tuple(acc))
            return
        for p in range(minpart, rem + 1):
            rec(rem - p, p, acc + [p])

    rec(u, 1, [])
    return res


def subalgebra_span(w, gens):
    """All weight-w products of Y-blocks (derivatives of the given
    generator pairs) and even X-monomials, as currents."""
    blks = []
    for pair in gens:
        blks += blocks(pair, w)
    elements = []

    def rec(start, wleft, acc):
        # acc: current product of Y-blocks (current dict)
        for xm in x_monos(wleft):
            elements.append(mult(acc, {(xm, ()): F(1)}))
        for i in range(start, len(blks)):
            cur, bw = blks[i]
            if bw <= wleft:
                rec(i, wleft - bw, mult(acc, cur))

    rec(0, w, {((), ()): F(1)})
    return [e for e in elements if e]


def membership(target, w, gens):
    """Is `target` (weight-w current) in subalgebra-span + Im d?
    Returns (member, remainder_support)."""
    basis = gen_mixed_basis(w)
    index = {m: i for i, m in enumerate(basis)}
    piv = SparsePivots()
    for b in gen_mixed_basis(w - 1):
        col = {}
        for m, c in d_mixed_mono(b).items():
            col[index[m]] = col.get(index[m], 0) + c
        col = {k: c for k, c in col.items() if c}
        if col:
            piv.insert(col)
    for el in subalgebra_span(w, gens):
        iv, _ = _to_int_vec(el, index)
        if iv:
            piv.insert(iv)
    iv, _ = _to_int_vec(target, index)
    r = piv.reduce(iv)
    if not r:
        return True, []
    support = sorted({basis[k][1] for k in r})
    return False, support


def main():
    GENS = (("A<=2 {X,(11)}", [(1, 1)]),
            ("A<=4 {X,(11),(22)}", [(1, 1), (2, 2)]),
            ("A<=6 {X,..,(33)}", [(1, 1), (2, 2), (3, 3)]),
            ("A<=8 {X,..,(44)}", [(1, 1), (2, 2), (3, 3), (4, 4)]))
    failures = []

    # retained controls (audit round 2: previously session-only)
    p11 = {((), ((1, 1),)): F(1)}
    p22 = {((), ((2, 2),)): F(1)}
    p33 = {((), ((3, 3),)): F(1)}
    shift = dict(p33)
    for m, c in d_cur({((), ((2, 3),)): F(5)}).items():
        shift[m] = shift.get(m, 0) + c
    shift = {m: c for m, c in shift.items() if c}
    controls = [
        ("(11)(22) in A<=4 (w6)", mult(p11, p22), 6, GENS[1][1], True),
        ("d-exact (23)-current in A<=4 (w6)",
         d_cur({((), ((2, 3),)): F(1)}), 6, GENS[1][1], True),
        ("(33)+5*d((23)) in A<=4 (w6)", shift, 6, GENS[1][1], False),
    ]
    for name, cur, w, gens, expect in controls:
        got, _ = membership({m: c for m, c in cur.items() if c}, w, gens)
        print(f"control {'PASS' if got == expect else 'FAIL'}: {name} "
              f"-> {got} (expect {expect})", flush=True)
        if got != expect:
            failures.append(f"control {name}")

    N, s = curve_point(F(2))
    verdicts = {}
    for sol in (1, 2, 3):
        P4 = cyl_P4(sol, N, s)
        reps = {3: P4}
        for sigma in (5, 7):
            g = genuine_kernel_sparse(
                P4, gen_mixed_basis(sigma + 1), N, residue_mixed_cur,
                gen_mixed_basis, d_mixed_mono, spin_mixed)
            if len(g) != 1:  # explicit: assert vanishes under -O
                print(f"FAILURES: kernel dim {len(g)} != 1 at "
                      f"sol {sol} sigma {sigma}", flush=True)
                print("CYL MEMBERSHIP COMPUTATION FAILED", flush=True)
                sys.exit(1)
            reps[sigma] = g[0]
        for sigma, cur in reps.items():
            w = sigma + 1
            for name, gens in GENS:
                ok, _ = membership(cur, w, gens)
                verdicts[(sol, sigma, name)] = ok
                print(f"sol {sol} I{sigma} (weight {w}) in {name}: "
                      f"{ok}", flush=True)

    # the six certified conditions, per solution
    for sol in (1, 2, 3):
        expected = [((sol, 3, GENS[0][0]), False),
                    ((sol, 3, GENS[1][0]), True),
                    ((sol, 5, GENS[1][0]), False),
                    ((sol, 5, GENS[2][0]), True),
                    ((sol, 7, GENS[2][0]), False),
                    ((sol, 7, GENS[3][0]), True)]
        for key, want in expected:
            if verdicts[key] != want:
                failures.append(f"{key} = {verdicts[key]}, want {want}")

    print()
    if failures:
        print(f"FAILURES: {failures}", flush=True)
        print("CYL MEMBERSHIP COMPUTATION FAILED", flush=True)
        sys.exit(1)
    print("VERDICT: finite-range ladder through I7 -- I3 closes at "
          "singlet spin 4, I5 at 6, I7 at 8, each failing one step "
          "lower.  The direct LV rank-2 W(2,4) match is excluded.  A "
          "finite W(2,4,6,8)-type closure containing all higher "
          "charges is NOT excluded by this finite-range computation.",
          flush=True)
    print("CYL MEMBERSHIP COMPUTATION COMPLETE", flush=True)


if __name__ == "__main__":
    main()
