"""The symmetric-pair {+-sqrt2} commutant at c=1: character
identification (the resolution of the q^8 clue).

CLAIM under test.  The momenta +-sqrt2 at c=1 have h = alpha^2/2 = 1
(asserted): they are the momenta of the SU(2)_1 currents J^+- at the
self-dual radius, and the two screening charges act on the U(1)
Fock module F_0 as the sl2 raising/lowering zero modes E, F of the
integrable level-1 vacuum module V_1 = (+)_n F_{n sqrt2} (J^3 = n
grading).  A vector killed by both E and F in an integrable module
is an sl2 SINGLET, so the joint {+-sqrt2} kernel should be exactly
the singlet sector of V_1, with character

    chi_singlet(q) = chi_{J3=0} - chi_{J3=1}
                   = (q^0 - q^1)/phi(q) = (1-q)/phi(q),

whose coefficients are p(w) - p(w-1) = p_{>=2}(w) (partitions with
no part equal to 1 -- the identity is asserted numerically).  Charge
(mod-d) dimensions then follow by differencing:

    dim charges(w) = p_{>=2}(w) - p_{>=2}(w-1)   for w >= 2.

WHAT IS CERTIFIED HERE (exact arithmetic end to end):
 1. the joint {+-sqrt2} kernel charge dimensions at ALL density
    weights 2..14, computed by restriction of scalars over Q(sqrt2)
    (full split vectors, sparse integer elimination) -- an
    arithmetic stack INDEPENDENT of the sympy-solve route that
    produced the certified weight 2..10 table in
    c1_enhanced_fingerprint.py;
 2. agreement with that certified table at weights 2..10
    (cross-stack validation) -- including the anomalous even-spin
    class at weight 9 (charge spin 8), which the singlet character
    PREDICTS rather than tolerates;
 3. the singlet-character prediction at the four NEW weights
    11..14 (a falsifiable test, not a tautology: these dimensions
    were never computed before);
 4. the partition identity p_{>=2}(n) = p(n) - p(n-1) (n <= 14)
    linking the Fock-character difference to the parts>=2 form;
 5. h(+-sqrt2) = 1 (the current dictionary), and the weight-1
    negative control: oint dX (the J^3 charge, an sl2 ADJOINT
    vector) is NOT in the joint kernel;
 6. anchor memberships tying the singlet space to the degeneracy
    story: at weight 4 the kernel contains the KdV I3 ray and NOT
    the enhanced I3' ray; at weight 6 it contains both the KdV and
    enhanced I5 classes (the certified dim-2 degeneracy).

STATUS: ALL-WEIGHT THEOREM (review round; citation VERIFIED against
the paper).  Dong-Griess, arXiv:q-alg/9710017, Corollary 2.4 (the
review cited 2.1, which is the adjacent equation label): for the A1
lattice VOA V_{L_2}, the weight-one Lie algebra g = (V_{L_2})_1 is
sl(2,C) and the g-invariant subVOA V_{L_2}^g is isomorphic to
L(1,0) -- the c = 1 VIRASORO VACUUM VOA -- with dim_q L(1,0) =
(1-q)/phi(q) from their displayed character formula at h = 0.
Since g-invariants must lie in the momentum-zero sector M(1) = F_0
(nonzero H-weight elsewhere), and E,F-killed vectors of F_0 are
automatically H-killed, our joint kernel IS V_{L_2}^g.  The charge
step: E, F are zero modes of weight-one elements, so they commute
with L_{-1}; each grade is a finite-dimensional semisimple
g-module (unitarity/(2.2) of the paper), invariants are exact, and
L_{-1} is injective in positive degree -- hence
(V/L_{-1}V)^g = V^g / L_{-1} V^g and

    dim charges(w) = p_{>=2}(w) - p_{>=2}(w-1)   for ALL w >= 2,

a theorem, not a conjecture.  The identification is also sharper
than 'singlet sector': L(1,0) is the subVOA generated by T, so the
symmetric-pair kernel consists exactly of the T-COMPOSITE charges
(explaining every anchor below, and connecting to the A2(2)
program's joint-kernel lemma).  The precise object is the
horizontal-sl2 FIXED-POINT subVOA V_{A1}^{sl2}, not an affine coset
commutant.  This certificate's 13-weight computation stands as
independent in-engine verification of the theorem's dimensions;
the sl2 closure itself is the cited standard structure."""
import sys
from fractions import Fraction as F

import sympy as sp

from families import KDV_P6
from ope_engine import d_mono, gen_basis
from screening_fit import residue_screen, screening_conditions, twisted_d
from sparse_linalg import SparsePivots, lcm

failures = []


def check(name, ok):
    print(f"{'PASS' if ok else 'FAIL'}  {name}", flush=True)
    if not ok:
        failures.append(name)


SQ2 = sp.sqrt(2)
NB = 2                                    # field basis {1, sqrt2}


def split2(expr):
    # exact inputs only -- no nsimplify (its numerical refitting
    # corrupts large rationals into radical-power garbage)
    e = sp.expand(expr)
    c1 = e.coeff(SQ2, 0)
    c2 = e.coeff(SQ2, 1)
    if sp.simplify(e - c1 - c2 * SQ2) != 0:
        raise ValueError(f"split failed: {e}")
    r1, r2 = sp.Rational(c1), sp.Rational(c2)
    return (F(int(r1.p), int(r1.q)), F(int(r2.p), int(r2.q)))


def mul_basis2(pair, bi):
    """(c1 + c2 sqrt2) * basis_bi in coordinates."""
    c1, c2 = pair
    return (c1, c2) if bi == 0 else (2 * c2, c1)


def int_vec(fr):
    L = 1
    for v in fr.values():
        L = lcm(L, v.denominator)
    return {i: int(v * L) for i, v in fr.items() if v}, L


def clone(piv):
    q = SparsePivots()
    q.rows = dict(piv.rows)
    return q


def dspan1(w):
    basis = gen_basis(w, 1, z2=False)
    idx = {m: i for i, m in enumerate(basis)}
    piv = SparsePivots()
    for bmono in gen_basis(w - 1, 1, z2=False):
        col = {}
        for m, c in d_mono(bmono).items():
            col[idx[m]] = col.get(idx[m], 0) + c
        col = {i: c for i, c in col.items() if c}
        if col:
            for beta in range(NB):
                piv.insert({i * NB + beta: c for i, c in col.items()})
    return basis, idx, piv


def joint_kernel(w):
    """Joint {+-sqrt2} kernel at one-boson density weight w as full
    split vectors over Q(sqrt2)."""
    basisw = gen_basis(w, 1, z2=False)
    tgt = gen_basis(w - 1, 1, z2=False)
    tidx = {m: i for i, m in enumerate(tgt)}
    lower = [()] if w == 2 else gen_basis(w - 2, 1, z2=False)
    nt = len(tgt)
    moms = [(SQ2,), (-SQ2,)]

    Rcols_s = [[{tidx[m]: split2(c) for m, c in
                 residue_screen({b: F(1)}, al).items()}
                for b in basisw] for al in moms]
    Tcols_s = [[{tidx[m]: split2(c) for m, c in
                 twisted_d(u_, al, 1).items()} for u_ in lower]
               for al in moms]

    bigcols, scales = [], []
    nx = len(basisw) * NB
    for j in range(len(basisw)):
        for bi in range(NB):
            col = {}
            for s in range(2):
                base = s * nt * NB
                for r, e in Rcols_s[s][j].items():
                    for beta, cv in enumerate(mul_basis2(e, bi)):
                        if cv:
                            kkey = base + r * NB + beta
                            col[kkey] = col.get(kkey, F(0)) + cv
            iv, L = int_vec(col)
            bigcols.append(iv)
            scales.append(L)
    for s in range(2):
        base = s * nt * NB
        for u_ in range(len(lower)):
            for bi in range(NB):
                col = {}
                for r, e in Tcols_s[s][u_].items():
                    for beta, cv in enumerate(mul_basis2(e, bi)):
                        if cv:
                            kkey = base + r * NB + beta
                            col[kkey] = col.get(kkey, F(0)) + cv
                iv, L = int_vec(col)
                bigcols.append(iv)
                scales.append(L)

    nc = len(bigcols)
    piv = SparsePivots()
    kers = []
    for jcol, col in enumerate(bigcols):
        aug = {i + nc: v for i, v in col.items()}
        aug[jcol] = 1
        r = piv.reduce(aug)
        if r and max(r) < nc:
            kers.append(r)
        elif r:
            piv.rows[max(r)] = r

    vecs = []
    for kv in kers:
        xv = {}
        for cidx, coef in kv.items():
            if cidx < nx:
                val = coef * scales[cidx]
                if val:
                    xv[cidx] = val
        if xv:
            vecs.append(xv)
    return basisw, vecs


def qdim(vecs, dpiv):
    q = clone(dpiv)
    return sum(1 for v in vecs if v and q.insert(dict(v)))


def member(t_base, vecs, dpiv, idx):
    q = clone(dpiv)
    for v in vecs:
        if v:
            q.insert(dict(v))
    fr = {}
    for m, c in t_base.items():
        if not isinstance(c, F):
            c = F(int(sp.numer(c)), int(sp.denom(c)))
        fr[idx[m] * NB] = fr.get(idx[m] * NB, F(0)) + c
    iv, _ = int_vec(fr)
    return not q.reduce(iv)


# ------- partition arithmetic ---------------------------------------
N = 15
p_all = [0] * (N + 1)
p_all[0] = 1
for part in range(1, N + 1):
    for n in range(part, N + 1):
        p_all[n] += p_all[n - part]
p_ge2 = [0] * (N + 1)
p_ge2[0] = 1
for part in range(2, N + 1):
    for n in range(part, N + 1):
        p_ge2[n] += p_ge2[n - part]
check("character identity: p_{>=2}(n) = p(n) - p(n-1) for n <= 14 "
      "(Fock difference (1-q)/phi(q) = parts>=2 form)",
      all(p_ge2[n] == p_all[n] - p_all[n - 1] for n in range(1, N)))

check("current dictionary: h(+-sqrt2) = alpha^2/2 = 1 (the SU(2)_1 "
      "current weight at the self-dual point)",
      sp.simplify(SQ2**2 / 2 - 1) == 0)

# weight-1 negative control: oint dX = J^3, adjoint not singlet
c_j3 = [x for x in screening_conditions({((1, 0),): F(1)}, (SQ2,), 1)
        if sp.simplify(x) != 0]
check("weight 1: oint dX (the J^3 charge) is NOT in the joint "
      "kernel (adjoint vector, negative control)", bool(c_j3))

# ------- the kernel dimensions, weights 2..14 -----------------------
FAST = len(sys.argv) > 1 and sys.argv[1] == "fast"
WMAX = 8 if FAST else 14
CERTIFIED_2_10 = [1, 0, 1, 0, 2, 0, 3, 1, 4]
dims = {}
keep = {}
for w in range(2, WMAX + 1):
    basisw, vecs = joint_kernel(w)
    _, _, dp = dspan1(w)
    qd = qdim(vecs, dp)
    check(f"w={w}: Q-dim {qd} divisible by 2 (Galois-stable system)",
          qd % NB == 0)
    dims[w] = qd // NB
    keep[w] = (basisw, vecs, dp)
    pred = p_ge2[w] - p_ge2[w - 1]
    print(f"w={w}: charge K-dim {dims[w]}  (singlet-character "
          f"prediction {pred})", flush=True)

check(f"weights 2..{min(WMAX, 10)} reproduce the certified "
      f"fingerprint table (independent arithmetic stack)",
      [dims[w] for w in range(2, min(WMAX, 10) + 1)]
      == CERTIFIED_2_10[:min(WMAX, 10) - 1])
for w in range(2, WMAX + 1):
    tag = ("NEW weight, falsifiable prediction" if w >= 11
           else "certified weight")
    check(f"w={w}: dim = p_ge2({w}) - p_ge2({w - 1}) "
          f"= {p_ge2[w] - p_ge2[w - 1]} ({tag})",
          dims[w] == p_ge2[w] - p_ge2[w - 1])
if FAST:
    # the pinned artifact is READ, not restated (review catch: a
    # hard-coded copy would pass with the artifact deleted); its
    # hash is additionally pinned in the certification registry
    import json as _json
    import re as _re
    import subprocess as _sub
    from pathlib import Path as _Path
    _root = _Path(__file__).resolve().parent.parent
    art = _json.load(open(_root / "results/symmetric_pair_dims.json"))
    adims = {int(w): d for w, d in art["dims_by_weight"].items()}
    check("artifact dims cover weights 2..14",
          sorted(adims) == list(range(2, 15)))
    check("artifact dims at recomputed weights 2..8 match this run",
          all(adims[w] == dims[w] for w in range(2, WMAX + 1)))
    check("artifact dims at pinned weights 9..14 match the theorem "
          "formula",
          all(adims[w] == p_ge2[w] - p_ge2[w - 1]
              for w in range(9, 15)))
    rc = art.get("run_commit", "")
    well_formed = bool(_re.fullmatch(r"[0-9a-f]{40}", rc))
    if (_root / "EXPORT_RECORD.json").exists():
        # Public certificate edition (two-tier provenance, Decision 2):
        # private-development SHAs are opaque archival references and
        # deliberately do not resolve here; require well-formedness
        # only, and let public_lint.py own content verification.
        check("artifact run_commit is a well-formed archival SHA "
              "(public edition: private history not resolvable by "
              "design)", well_formed)
    else:
        ok_commit = well_formed and (
            _sub.run(["git", "cat-file", "-e", rc + "^{commit}"],
                     cwd=_root, capture_output=True).returncode == 0)
        check("artifact run_commit is a full SHA resolving in this "
              "repository", ok_commit)

# ------- anchors ----------------------------------------------------
KDV_I3 = {((1, 0),) * 4: F(1), ((2, 0), (2, 0)): F(-2)}
I3P_RAY = {((1, 0),) * 4: F(2), ((1, 0), (3, 0)): F(-5)}
A2_P6 = {((3, 0), (3, 0)): F(31, 24),
         ((1, 0), (1, 0), (2, 0), (2, 0)): F(5, 2),
         ((1, 0),) * 6: F(1)}
KDV6 = dict(KDV_P6)

b4, v4, dp4 = keep[4]
_, idx4, _ = dspan1(4)
check("weight 4: the KdV I3 ray IS in the singlet space",
      member(KDV_I3, v4, dp4, idx4))
check("weight 4: the enhanced I3' ray is NOT in the singlet space",
      not member(I3P_RAY, v4, dp4, idx4))
b6, v6, dp6 = keep[6]
_, idx6, _ = dspan1(6)
check("weight 6: the enhanced I5 class IS in the singlet space",
      member(A2_P6, v6, dp6, idx6))
check("weight 6: the KdV I5 class IS in the singlet space (the "
      "certified dim-2 degeneracy, both members identified)",
      member(KDV6, v6, dp6, idx6))

print()
if failures:
    print(f"FAILURES: {failures}")
    print("SYMMETRIC-PAIR CHARACTER FAILED")
    sys.exit(1)
if FAST:
    print("SYMMETRIC-PAIR CHARACTER FAST SUITE PASSED (weights 2..8 "
          "recomputed; 9..14 pinned from the registered full run)")
else:
    print("SYMMETRIC-PAIR CHARACTER IDENTITY CERTIFIED (weights "
          "2..14): the joint {+-sqrt2} kernel is the horizontal-sl2 "
          "fixed-point subVOA V_{A1}^{sl2} = L(1,0), the c=1 "
          "Virasoro vacuum algebra (Dong-Griess Cor 2.4, verified) "
          "-- the T-composite charges -- and "
          "dim(w) = p_ge2(w) - p_ge2(w-1) holds as an ALL-WEIGHT "
          "THEOREM, independently verified here at 13 consecutive "
          "weights including the even-spin class at charge spin 8.")
print("SYMMETRIC-PAIR CHARACTER COMPLETE")
